<?php

use Illuminate\Database\Seeder;
use App\Models\Currency\Currency;
use Carbon\Carbon;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            [
                'id' => 'f32b2332-da55-4eb4-8e86-3b20aac09b58',
                'name' => 'TL',
                'crypto' => false,
                'short_name' => 'TL',
                'long_name' => 'Türk Lirası',
                'decimal' => 2,
                'order' => 1,
                'icon' => 'fa fa-try',
                'color_code' => '',
                'tx_url' => '',
                'address_url' => '',
                'withdraw_description' => '',
                'deposit_description' => '',
                'approval_number' => null,
                'exchange_min' => 1,
                'exchange_max' => 800,
                'deposit_min' => 100,
                'deposit_max' => 50000,
                'withdraw_min' => 100,
                'withdraw_max' => 50000,
                'active' => true,
                'exchange' => true,
                'deposit' => true,
                'withdraw' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 'c40e437e-4b46-4dc7-b1d5-5bd40198d3d4',
                'name' => 'BTC',
                'crypto' => true,
                'short_name' => 'BTC',
                'long_name' => 'Bitcoin',
                'decimal' => 8,
                'order' => 2,
                'color_code' => '#fa7000',
                'logo' => '/imgs/uploads/currency/btc.png',
                'icon' => 'cf cf-btc',
                'tx_url' => 'https://btc.com/',
                'address_url' => 'https://btc.com/',
                'approval_number' => 3,
                'exchange_min' => 0.001,
                'exchange_max' => 1,
                'deposit_min' => 0.001,
                'deposit_max' => 1,
                'withdraw_min' => 1,
                'withdraw_max' => 1,
                'active' => true,
                'exchange' => true,
                'deposit' => true,
                'withdraw' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '6029412e-8b7f-4889-a9b9-c862317b0dd8',
                'name' => 'LTC',
                'crypto' => true,
                'short_name' => 'LTC',
                'long_name' => 'Litecoin',
                'decimal' => 8,
                'order' => 3,
                'color_code' => '#808080',
                'logo' => '/imgs/uploads/currency/ltc.png',
                'icon' => 'cf cf-ltc',
                'tx_url' => 'https://chainz.cryptoid.info/ltc/tx.dws?',
                'address_url' => 'https://chainz.cryptoid.info/ltc/address.dws?',
                'approval_number' => 6,
                'exchange_min' => 0.001,
                'exchange_max' => 1,
                'deposit_min' => 0.001,
                'deposit_max' => 1,
                'withdraw_min' => 1,
                'withdraw_max' => 1,
                'active' => true,
                'exchange' => true,
                'deposit' => true,
                'withdraw' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '03d903b3-4c2b-4a03-aaca-eab9d38cb937',
                'name' => 'ETH',
                'crypto' => true,
                'short_name' => 'ETH',
                'long_name' => 'Ethereum',
                'decimal' => 8,
                'order' => 4,
                'color_code' => '#696dff',
                'logo' => '/imgs/uploads/currency/eth.png',
                'icon' => 'cf cf-eth',
                'tx_url' => 'https://etherscan.io/tx/',
                'address_url' => 'https://etherscan.io/address/',
                'approval_number' => 15,
                'exchange_min' => 0.001,
                'exchange_max' => 1,
                'deposit_min' => 0.001,
                'deposit_max' => 1,
                'withdraw_min' => 1,
                'withdraw_max' => 1,
                'active' => true,
                'exchange' => true,
                'deposit' => true,
                'withdraw' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '992d17f4-b78f-4ca3-be85-30a03f634361',
                'name' => 'DASH',
                'crypto' => true,
                'short_name' => 'DASH',
                'long_name' => 'Dash',
                'decimal' => 8,
                'order' => 5,
                'color_code' => '#1f9eff',
                'logo' => '/imgs/uploads/currency/dash.png',
                'icon' => 'cf cf-dash',
                'tx_url' => 'https://chainz.cryptoid.info/dash/tx.dws?',
                'address_url' => 'https://chainz.cryptoid.info/dash/address.dws?/',
                'approval_number' => 6,
                'exchange_min' => 0.001,
                'exchange_max' => 1,
                'deposit_min' => 0.001,
                'deposit_max' => 1,
                'withdraw_min' => 1,
                'withdraw_max' => 1,
                'active' => true,
                'exchange' => true,
                'deposit' => true,
                'withdraw' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]

        ];

        foreach ($currencies as $currency) {
            Currency::insert($currency);
        }
    }
}
